id: P25C7ACCE
initial_creation_type: input
source_metadata:
  title: Parting from the Four Attachments
  language: bo
  description: 'A series of texts related to the famous four-line instruction that
    Sachen Kunga Nyingpo (1092–1158) received from Mañjuśrī:'
  volume:
    5dfa4f56b6c14bf6894522bc10f78077:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      parent: Lineage Prayers
    b18e3e12354a46e5bc72d9e2c324f95b:
      title: Prayer to the Lineage of Parting from the Four Attachments
      parent: Lineage Prayers
    18ffc23a1965444f9848226bb4efdc65:
      title: The Instructions on Parting from the Four Attachments
      parent: Root Text
    efdc927e1c38413e8f615cf361d40899:
      title: Parting from the Four Attachments
      parent: Commentaries
    2d8fe199976741acb25dd60dc3e89de3:
      title: Nubpa Rigdzin Drak's Parting from the Four Attachments
      parent: Commentaries
    f72bdff0879f4c359d5c4a2529d3214f:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Commentaries
    3536d6e69c904575b32058f68e1e3596:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: Song
created_at: '2022-03-01T05:02:13.483206'
last_modified_at: '2022-03-01T05:02:13.483210'
statistics:
  total_words: 3092
  total_non_words: 192
quality:
  non_words_ratio: 0.06
